### ISSUE TITLE
Please provide version tags for tonistiigi/xx:golang

### ISSUE THREAD

**Issue by moikot** [tonistiigi/xx#10]
I've been using successfully tonistiigi/xx:golang for compiling my golang apps to different architectures including linux/386 (with CGO_ENABLED=0) because the image was not a multi-arch one. The last one is targeting different architectures but linux/386 is not among them and my build started to fail. Unfortunately, I can't pick the previous (non-manifest v2) image because this image doesn't contain a version in its tag. 
Since this image is widely popular and used in multiple builds would it be possible to add version tags or maybe produce an arch-agnostic image that supports builds with CGO_ENABLED=0?

**Comment by tonistiigi** [comment]
```
» docker buildx imagetools inspect tonistiigi/xx:golang-1.0.0                                                                                                               !10119
{
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "schemaVersion": 2,
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "digest": "sha256:93a2e48acc0d1737321cd70c0fb0a8d639e9542b8875b0410ca845dbbeaa365f",
      "size": 458
   },
   "layers": [
      {
         "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
         "digest": "sha256:3163ff2fb1467b18ab01419a9fb48e016ac4fe7ffdc8b3822ebe1298bc3ecb53",
         "size": 687
      }
   ]
}
```

https://github.com/tonistiigi/xx/tree/golang/v1.0.0

**Comment by moikot** [comment]
Thanks a lot!
