### ISSUE TITLE
Ubuntu 24.04 support

### ISSUE THREAD

**Issue by tatsuhiro-t** [tonistiigi/xx#166]
I updated Dockerfile that works with Ubuntu 22.04 to 24.04, then arm64 cross build started failing because xx-apt-get failed to get package lists.  It looks like apt source rewrite does not work properly.  Will debug it more.

**Comment by crazy-max** [comment]
Can you try with latest release https://github.com/tonistiigi/xx/releases/tag/v1.5.0 and let us know?

**Comment by tatsuhiro-t** [comment]
Could you push 1.5.0 image to docker hub?

**Comment by tatsuhiro-t** [comment]
Instead, I tried master image and it worked perfectly.  Will try 1.5.0 once it is available on docker hub.

**Comment by crazy-max** [comment]
Ah my bad the `1.5.0` can't be built because of #167 

Can you try with `tonistiigi/xx:master` instead?

**Comment by tatsuhiro-t** [comment]
tonistiigi/xx:master works for me.  I close this issue because the fix has already been done.  Will wait for 1.5.0 image.  Thank you.

**Comment by crazy-max** [comment]
`tonistiigi/xx:1.5.0` and `tonistiigi/xx:latest` are good now.
