### ISSUE TITLE
Remove base directory

### ISSUE THREAD

**Issue by tonistiigi** [tonistiigi/xx#58]
It doesn't make sense to have the source code under `base/`. Initially I imagined a bit different layout and multiple variants of xx that doesn't seem to be needed.

Should be moved to either root or under `/src`.

When we add additional things like break out sigtool etc https://github.com/tonistiigi/xx/blob/master/base/Dockerfile#L208 then these can be under `tools/` or in their own directory.

**Comment by crazy-max** [comment]
> Should be moved to either root or under `/src`.

This one sgtm
