### ISSUE TITLE
Docker image of ekuiper

### ISSUE THREAD

**Issue by kush930** [tonistiigi/xx#61]
Hi all, 

Issue : Not able docker image ekuiper on target riscv(native build).
Reproduces:
*Git clone https://github.com/lf-edge/ekuiper.git
*Cd ekuiper
*make build_with_edgex
*make pkg_with_edgex

Binary file and package was successful.

root@lavkhush-3:~ekuiper# make docker
docker buildx build --no-cache --platform=linux/riscv64 -t lfedge/ekuiper:1.4.0-14-g2f9bba1 -f deploy/docker/Dockerfile . --load
[+] Building 655.9s (8/13)
=> [internal] load build definition from Dockerfile 0.1s
=> => transferring dockerfile: 32B 0.0s
=> [internal] load .dockerignore 0.7s
=> => transferring context: 2B 0.6s
=> **[internal] load metadata for docker.io/tonistiigi/xx:golang-riscv 0.0s**
=> [internal] load build context 5.1s
=> => transferring context: 797.61kB 3.6s
=> CACHED [1/9] FROM docker.io/tonistiigi/xx:golang-riscv 0.0s
=> [2/9] COPY . /go/kuiper 648.3s
=> [3/9] WORKDIR /go/kuiper 0.3s
=> **ERROR [4/9] RUN apt-get update && apt-get install -y pkg-config libczmq-dev 1.4s**
------
> [4/9] RUN apt-get update && apt-get install -y pkg-config libczmq-dev:
#8 1.226 {"msg":"exec the container process: Exec format error","level":"error","time":"2022-01-05T11:16:51.000418472Z"}
------
error: failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c apt-get update && apt-get install -y pkg-config libczmq-dev]: runc did not terminate sucessfully
make: *** [Makefile:72: docker] Error 1

I have already installed pkg-config and czmq on my target riscv , binary also created, then also i am facing this issue, please guide me, if anything is missing.

T&R
Kush Kumar

**Comment by tonistiigi** [comment]
I don't see the relevance of this question to `xx`. Don't see it used in https://github.com/lf-edge/ekuiper/blob/master/deploy/docker/Dockerfile neither is your build failing on running an xx command.
